AIGNE-io/aigne-framework

- examples/mcp-server-github-integrator/.env.local.example
- examples/mcp-server-github-integrator/CHANGELOG.md
- examples/mcp-server-github-integrator/README.md
- examples/mcp-server-github-integrator/index.ts
- examples/mcp-server-github-integrator/package.json
- examples/mcp-server-github-integrator/tsconfig.json
- examples/mcp-server-github-integrator/usages.ts
- packages/core/src/agents/mcp-agent.ts
- pnpm-lock.yaml
- chore(example): add mcp-server-github-integrator example
- fix: resolve the bug of StdioClientTransport missing default env
// test index.ts
https://github.com/blocklet/media-kit/issues/383
// test usages.ts
> chore(example): add mcp-server-github-integrator example

- packages/core/src/agents/mcp-agent.ts
- packages/core/test/agents/mcp-agent.test.ts
1. set default timeout to 60s and support change timeout by env `MCP_TIMEOUT` or `TIMEOUT`
**Chore**: 
- Increased default MCP client timeout from 10s to 60s for improved reliability in high-latency environments
- Added configurable timeout via `MCP_TIMEOUT` or `TIMEOUT` environment variables
This change enhances system stability by providing more generous default timeouts and flexibility in configuring timeout values according to specific deployment needs. Users experiencing timeout issues in their environments can now adjust these values without code modifications.
> fix(core): set default mcp timeout to 60s

- .github/workflows/test-examples.yml
- packages/core/src/agents/ai-agent.ts
- packages/core/src/models/chat-model.ts
- packages/core/src/models/open-router-chat-model.ts
- packages/core/src/models/openai-chat-model.ts
https://github.com/AIGNE-io/aigne-framework/issues/66
1. fix: enhance router toolChoice validation to support parallel tool calls
2. feat(ci): add new Gemini model for test
3. feat(ci): update exclude pattern in test-examples workflow
New Feature: Added parallel tool execution support
- Enables compatible AI models to process multiple tool calls simultaneously, improving performance and efficiency
- Automatically validates and enforces model capabilities to ensure safe parallel execution
- OpenRouter models currently do not support parallel tool calls and will maintain sequential execution
This enhancement allows supported AI models to handle concurrent tool operations while maintaining compatibility with models that require sequential processing.
> fix(core): support dynamic model capability detection

- LICENSE
- README.md
- README.zh.md
- examples/chat-bot/package.json
- examples/mcp-blocklet/package.json
- examples/mcp-github/package.json
- examples/mcp-puppeteer/package.json
- examples/mcp-sqlite/package.json
- examples/workflow-code-execution/package.json
- examples/workflow-concurrency/package.json
- examples/workflow-group-chat/package.json
- examples/workflow-handoff/package.json
- examples/workflow-orchestrator/package.json
- examples/workflow-reflection/package.json
- examples/workflow-router/package.json
- examples/workflow-sequential/package.json
- package.json
- packages/agent-library/README.md
- packages/agent-library/README.zh.md
- packages/agent-library/package.json
- packages/cli/README.md
- packages/cli/README.zh.md
- packages/cli/package.json
- packages/core/README.md
- packages/core/README.zh.md
- packages/core/package.json
1. add README for subpackages
2. update license to Elastic-2.0
- Chore: Added MIT License to the project, enabling users and developers to freely use, modify, and distribute the software under standard open-source terms
This foundational change establishes clear usage rights and legal protections for the project under AIGNE.io's copyright, following open-source best practices.
> docs: add README for subpackages & update license

- packages/cli/test/_mocks_/mock-aigne-package.ts
- packages/core/src/models/claude-chat-model.ts
- packages/core/src/models/openai-chat-model.ts
- packages/core/src/utils/stream-utils.ts
- packages/core/test/_utils/openai-like-utils.ts
- packages/core/test/models/__snapshots__/claude-chat-model.test.ts.snap
- packages/core/test/models/claude-chat-model.test.ts
- packages/core/test/models/claude-streaming-response-text.txt
1. feat(core): enhance ClaudeChatModel to support streaming responses
Release Notes:
- New Feature: Added streaming support to ClaudeChatModel, enabling real-time response processing
- Test: Enhanced test coverage for Claude chat model with streaming scenarios
- Test: Added comprehensive test utilities and sample data for model testing
These changes improve the Claude integration by supporting streaming responses, allowing for more efficient real-time processing of AI responses. Users can now receive and process Claude's responses incrementally rather than waiting for the complete response.
> feat(core): enhance ClaudeChatModel to support streaming responses

- .github/workflows/test-examples.yml
- examples/chat-bot/index.test.ts
- examples/chat-bot/tsconfig.json
- examples/mcp-blocklet/tsconfig.json
- examples/mcp-puppeteer/tsconfig.json
- examples/mcp-sqlite/tsconfig.json
- examples/workflow-code-execution/README.md
- examples/workflow-code-execution/index.ts
- examples/workflow-code-execution/tsconfig.json
- examples/workflow-code-execution/usage.ts
- examples/workflow-concurrency/tsconfig.json
- examples/workflow-orchestrator/tsconfig.json
- examples/workflow-reflection/tsconfig.json
- examples/workflow-router/tsconfig.json
- examples/workflow-sequential/tsconfig.json
- packages/core/package.json
- packages/core/src/loader/index.ts
- packages/core/src/models/bedrock-chat-model.ts
- packages/core/src/models/chat-model.ts
- packages/core/src/models/gemini-chat-model.ts
- packages/core/src/models/openai-chat-model.ts
- packages/core/src/utils/prompts.ts
- packages/core/test/models/__snapshots__/bedrock-chat-model.test.ts.snap
- packages/core/test/models/bedrock-chat-model.test.ts
- packages/core/test/models/bedrock-streaming-response-1.txt
- packages/core/test/models/bedrock-streaming-response-2.txt
- packages/core/test/models/bedrock-streaming-response-text.txt
- packages/core/test/utils/prompts.test.ts
- pnpm-lock.yaml
1. feat(core): support bedrock adapter
2. feat(core): minor refactor of the OpenAI chat model 
3. feat(tests): Minor refactor of the chat-bot test
Release Notes:
- New Feature: Added AWS Bedrock integration, enabling support for Amazon's foundation models
- New Feature: Implemented streaming support for tool calls in OpenAI models
- Enhancement: Improved JSON output handling and instruction clarity
- Chore: Streamlined model configurations by removing deprecated OpenRouter GPT-4 and Ollama models
- Test: Added comprehensive test coverage for AWS Bedrock integration
These changes expand available model options through AWS Bedrock integration and enhance streaming capabilities for tool interactions. Users can now leverage Amazon's foundation models alongside existing providers while …
> feat(core): add BedrockChatModel support

- .github/workflows/test-examples.yml
- examples/chat-bot/agents/chat.yaml
- examples/chat-bot/agents/sandbox.js
- examples/chat-bot/agents/sandbox.test.js
- examples/workflow-code-execution/index.ts
- examples/workflow-router/index.ts
- packages/core/src/models/bedrock-chat-model.ts
- packages/core/src/prompt/template.ts
- packages/core/src/utils/prompts.ts
- packages/core/test/models/__snapshots__/bedrock-chat-model.test.ts.snap
- packages/core/test/models/bedrock-chat-model.test.ts
- packages/core/test/models/bedrock-streaming-response-1.txt
- packages/core/test/models/bedrock-streaming-response-2.txt
- packages/core/test/models/bedrock-structured-response-3.json
- packages/core/test/utils/__snapshots__/prompts.test.ts.snap
- packages/core/test/utils/prompts.test.ts
https://github.com/AIGNE-io/aigne-framework/issues/110
https://github.com/AIGNE-io/aigne-framework/issues/104
1. Improve the accuracy of example-chat-bot prompt
2. Improved Bedrock structure output stability
3. Add CI support for the Nova series models
- Chore: Updated model names in CI configuration from "grok-3-mini" and "grok-2-latest" to "grok-3" and "grok-2" respectively to align with current XAI provider naming conventions
This is an internal maintenance update that ensures our CI pipeline uses the correct model identifiers. No functional changes or user-facing impacts.
> feat: optimize the stability of ci and example

- .github/workflows/test-examples.yml
- packages/core/src/prompt/template.ts
- packages/core/test/prompt/template.test.ts
1. feat: optimize the stability of the model and ci
> fix: optimize the stability of the model and ci

- packages/core/src/agents/agent.ts
- packages/core/src/agents/ai-agent.ts
- packages/core/src/aigne/context.ts
- packages/core/src/prompt/prompt-builder.ts
- packages/core/src/utils/stream-utils.ts
- packages/core/src/utils/type-utils.ts
- packages/core/test/agents/agent.test.ts
1. feat(core): add hooks support for agent
usage:
```ts
const model = new OpenAIChatModel();
const aigne = new AIGNE({ model });
const weather = FunctionAgent.from({
name: "weather",
description: "Get the weather of a city",
inputSchema: z.object({
city: z.string(),
}),
outputSchema: z.object({
temperature: z.number(),
}),
process: async (_input) => {
return {
temperature: 25,
};
},
});
const agent = AIAgent.from({
hooks: {
onStart: (event) => {
console.log("Agent started:", event.input);
},
onEnd: (event) => {
console.log("Agent ended:", event.input, event.output);
},
onSkillStart: (event) => {
console.log(`Skill ${event.skill.name} started:`, event.input);
},
onSkillEnd: (event) => {
console.log(
`Skill ${event.skill.name} ended:`,
event.input,
event.output,
);
},
},
skills: [weather], …
```
> feat(core): support lifecycle hooks for agent

- .github/workflows/test-examples.yml
- packages/cli/src/utils/listr.ts
- packages/cli/src/utils/run-chat-loop.ts
- packages/cli/src/utils/run-with-aigne.ts
- fix(cli): listr ctx maybe undefined
- none
Release Notes:
- Refactor: Improved agent handling in CLI chat mode for better reliability
- Bug Fix: Resolved potential undefined context errors in CLI task execution
- Chore: Standardized agent type naming across CLI components
These changes enhance the stability and consistency of the CLI experience, particularly in chat mode interactions. Users should notice more reliable agent behavior and fewer potential error scenarios during task execution.
> fix(cli): listr ctx maybe undefined

- packages/publish-docs/src/index.ts
- packages/publish-docs/src/publisher.ts
- packages/publish-docs/src/types.ts
- scripts/publish-docs.ts
1. refactor: update publishDocs and handle error reporting
- Refactor: Updated error messages in docs publishing to use correct terminology ("docs post" instead of "blog post"), improving clarity of error reporting for users
The change ensures more accurate and consistent error messaging when publishing documentation fails, helping users better understand the context of any publishing errors they encounter.
> refactor: update publishDocs and handle error reporting

- packages/publish-docs/src/converter/index.ts
- packages/publish-docs/src/generator.ts
1. fix: blank file handling in converter
- New Feature: Added detection and reporting of blank markdown files in documentation processing
- Bug Fix: Improved handling of empty markdown files to prevent unnecessary processing
- Enhancement: Added warning messages to help developers identify blank documentation files during build
These changes improve the robustness of the documentation publishing system by gracefully handling empty files and providing clearer feedback to content authors when blank files are encountered in the documentation set.
> fix: blank file handling in converter

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- .github/workflows/test-examples.yml
- biome.json
- examples/browser/browser.test.ts
- examples/browser/package.json
- examples/browser/src/main.tsx
- packages/core/src/index.ts
- packages/core/src/utils/stream-polyfill.ts
- packages/core/src/utils/stream-utils.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
1. fix(core): add async generator polyfill for ReadableStream on safari
- none
- New Feature: Added ReadableStream polyfill for improved Safari browser compatibility
- Bug Fix: Resolved streaming functionality issues in Safari by implementing missing `values()` method and async iterator support
These changes ensure consistent streaming behavior across all major browsers, particularly benefiting Safari users who previously experienced limitations with stream functionality.
> fix(core): add async generator polyfill for ReadableStream on safari

- .github/workflows/main.yml
- fix: publish blocklet ci
Release Notes:
- Chore: Updated development toolchain with latest runtimes (Node.js v23, pnpm v10)
- New Feature: Added Bun runtime support for improved build performance
- Chore: Simplified build step naming for better workflow readability
These infrastructure updates ensure the project stays current with modern JavaScript tooling while adding support for the Bun runtime environment. The changes focus on improving the development experience without impacting end-user functionality.
> fix(blocklet): publish blocklet ci

- blocklets/observability/api/src/index.ts
- blocklets/observability/api/third.d.ts
- blocklets/observability/src/App.tsx
- blocklets/observability/src/contexts/session.tsx
- blocklets/observability/src/list.tsx
- docs/cli/observability.md
- docs/cli/observability.zh.md
- packages/cli/package.json
- packages/cli/src/commands/aigne.ts
- packages/cli/src/commands/observability.ts
- packages/core/src/aigne/aigne.ts
- packages/observability/api/core/db-path.ts
- packages/observability/api/core/type.ts
- packages/observability/api/observer/aigne-observer.node.ts
- packages/observability/api/opentelemetry/exporter/http-exporter.ts
- packages/observability/api/server/index.ts
- packages/observability/api/server/routes/trace.ts
- packages/observability/api/third.d.ts
- packages/observability/package.json
- packages/observability/src/components/run/AgentTag.tsx
- packages/observability/src/list.tsx
- pnpm-lock.yaml
- relate: https://team.arcblock.io/task/task/576967847180238848
- only the admin permission can access the data of the current page
- dynamically import blocklet/sdk will cause the agine/cli to run an error
Release Notes:
- Refactor: Improved list component architecture for better performance and maintainability
- New Feature: Enhanced session management with role-based access control for trace API
- New Feature: Added admin-only restrictions for sensitive operations
- Style: Refined AgentTag component visual presentation
- Bug Fix: Resolved session handling issues in list component
These changes improve system security, enhance user interface consistency, and provide better access control for administrative functions. Users will experience more reliable list operations and clearer visual …
> fix(blocklet): ensure only admins can access traces

- packages/agent-library/src/default-memory/default-memory-storage/index.ts
- packages/agent-library/src/default-memory/index.ts
- packages/agent-library/test/default-memory/__snapshots__/default-memory-storage.test.ts.snap
- packages/agent-library/test/default-memory/__snapshots__/default-memory.test.ts.snap
- packages/agent-library/test/default-memory/default-memory-storage.test.ts
- packages/agent-library/test/default-memory/default-memory.test.ts
- packages/agent-library/test/fs-memory/fs-memory.test.ts
- packages/core/src/agents/agent.ts
- packages/core/src/memory/memory.ts
- packages/core/src/memory/recorder.ts
- packages/core/src/memory/retriever.ts
- packages/core/src/utils/type-utils.ts
- packages/core/test/prompt/prompt-builder.test.ts
- packages/core/test/utils/type-utils.test.ts
- packages/transport/package.json
- packages/transport/src/http-client/client-agent.ts
- packages/transport/test/http-client/__snapshots__/http-client.test.ts.snap
- packages/transport/test/http-client/http-client.test.ts
- pnpm-lock.yaml
1. fix(core): pass input/output to MemoryAgent directily
Refactor: Memory System Overhaul
- Refactor: Restructured memory system from role-based to input/output format for improved consistency
- New Feature: Enhanced search capabilities supporting both string and message-based queries
- New Feature: Improved text segmentation and query handling for better memory retrieval
- Test: Updated test suite to reflect new memory architecture
This update streamlines the memory management system, making it more flexible and efficient. Users will experience more accurate memory retrieval and better handling of conversational context. No breaking changes to existing APIs.
> fix(core): pass input/output to MemoryAgent directily

- models/openai/src/openai-chat-model.ts
- packages/agent-library/src/default-memory/index.ts
- packages/agent-library/src/orchestrator/index.ts
- packages/cli/src/utils/listr.ts
- packages/core/src/agents/agent.ts
- packages/core/src/agents/ai-agent.ts
- packages/core/src/agents/chat-model.ts
- packages/core/src/agents/mcp-agent.ts
- packages/core/src/agents/team-agent.ts
- packages/core/src/agents/user-agent.ts
- packages/core/src/aigne/aigne.ts
- packages/core/src/aigne/context.ts
- packages/core/src/memory/memory.ts
- packages/core/src/memory/recorder.ts
- packages/core/src/memory/retriever.ts
- packages/core/src/prompt/template.ts
- packages/core/src/utils/type-utils.ts
- packages/core/test/_mocks/mock-memory.ts
- packages/core/test/utils/type-utils.test.ts
- packages/publish-docs/src/converter/nodes/image-node.ts
- packages/publish-docs/src/converter/nodes/mermaid-node.ts
- packages/transport/src/constants.ts
- packages/transport/src/http-client/client-agent.ts
- packages/transport/src/http-client/client-chat-model.ts
- packages/transport/src/http-client/client.ts
- packages/transport/src/http-server/server.ts
- packages/transport/test/_mocks_/mock-memory.ts
- packages/transport/test/http-client/__snapshots__/http-client.test.ts.snap
- packages/transport/test/http-client/http-client.test.ts
- tsconfig.json
1. feat(transport): support invoke server side chat model
2. chore(ts): enable noImplicitOverride and fix missing override modifiers
3. fix(core): skip span if observer is not set
Release Notes:
- Refactor: Enabled strict type checking with `noImplicitOverride` across the codebase for improved type safety
- New Feature: Added server-side chat model support in HTTP transport layer
- Refactor: Enhanced memory system type consistency and validation
- Refactor: Improved agent system type definitions and validation logic
- Chore: Standardized method overrides across document processing nodes
These changes primarily focus on improving type safety and consistency throughout the framework while adding server-side chat model capabilities. The updates maintain backward compatibility while …
> feat(transport): support invoke server side chat model

- packages/core/src/agents/agent.ts
- packages/core/test/_utils/expect.ts
- packages/core/test/agents/agent.test.ts
1. chore: add AgentInput/AgentOutput type utils to infer input/output type of agent
- New Feature: Enhanced TypeScript type utilities for improved Agent type inference and validation
- Test: Added comprehensive type testing utilities for better development experience
- Refactor: Improved type safety and inference capabilities for Agent input/output handling
These changes provide developers with better tooling for working with Agent types, reducing potential type-related errors and improving code reliability. The enhanced type system makes it easier to correctly implement and validate Agent interfaces.
> chore: add AgentInput/AgentOutput type utils to infer input/output type of agent

- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/utils/run-with-aigne.ts
- pnpm-lock.yaml
1. feat(cli): auto-load dotenv files for AIGNE CLI
- New Feature: Added support for `.env` files in the CLI using dotenv-flow, allowing more flexible configuration management
- New Feature: Environment variable support for model selection via `MODEL` env var, providing an alternative to command-line arguments
- Enhancement: Improved configuration flexibility by supporting both environment variables and CLI arguments for key settings
These updates make it easier to manage AIGNE CLI configurations across different environments without modifying command-line arguments.
> feat(cli): auto-load dotenv files for AIGNE CLI

- observability/api/api/server/migrate.ts
- observability/api/api/server/migrations/002-add-componentId.ts
- observability/api/api/server/migrations/003-add-action.ts
- observability/api/api/server/models/trace.ts
- observability/api/api/server/routes/trace.ts
- observability/ui/src/list.tsx
- observability/ui/src/locales/en.ts
- observability/ui/src/locales/zh.ts
> chore: delete span

- README.md
- biome.json
- models/anthropic/package.json
- models/anthropic/src/anthropic-chat-model.ts
- models/anthropic/src/global.d.ts
- models/anthropic/test/__snapshots__/anthropic-chat-model.test.ts.snap
- models/anthropic/test/anthropic-chat-model.test.ts
- models/gemini/test/__snapshots__/gemini-chat-model.test.ts.snap
- models/openai/package.json
- models/openai/src/global.d.ts
- models/openai/src/openai-chat-model.ts
- models/openai/test/openai-chat-model.test.ts
- pnpm-lock.yaml
1. fix(model): reduce unnecessary LLM requests for structured output
- New Feature: Improved JSON output handling for Anthropic and OpenAI chat models, enabling more efficient structured responses
- Performance: Optimized token usage and reduced unnecessary API calls when processing JSON responses
- Test: Added comprehensive test coverage for JSON output scenarios
- Refactor: Enhanced JSON parsing reliability with new jaison library integration
These changes result in faster response times and lower API costs when requesting structured output from language models, while maintaining robust error handling and validation.
> feat(model): reduce unnecessary LLM requests for structured output

- models/anthropic/src/anthropic-chat-model.ts
- models/bedrock/src/bedrock-chat-model.ts
- models/bedrock/test/bedrock-chat-model.test.ts
- models/openai/src/openai-chat-model.ts
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/utils/run-with-aigne.ts
- packages/cli/test/cli.test.ts
- packages/cli/test/commands/test.test.ts
- packages/core/src/aigne/aigne.ts
- packages/core/src/loader/agent-yaml.ts
- packages/core/src/loader/index.ts
- packages/core/test/loader/loader.test.ts
- pnpm-lock.yaml
1. fix(cli): print pretty error message for cli
example 1: aigne.yaml not found
```shell
$ npx aigne run
✔ Prepare environment [0.0s]
✖ Initialize AIGNE
Error: aigne.yaml not found in /Users/chao/Projects/blocklet/aigne-framework/examples/mcp-puppeteer. Please ensure you are in the correct directory or provide a valid path.
```
example 2: `--entry-agent` not found
```shell
npx aigne run --entry-agent foo
✔ Prepare environment [0.0s]
✔ Initialize AIGNE [0.0s]
Install the CLI first with: npm install -g @aigne/cli, then run aigne observe to start the observability server.
Error: Agent "foo" not found in /Users/chao/Projects/blocklet/aigne-framework/examples/chat-bot
Available agents:
- chat
```
Release Notes:
- Refactor: Simplified error messages in CLI for better readability with colored …
> fix(cli): print pretty error message for cli

- observability/blocklet/blocklet.yml
- observability supports composability
- New Feature: Added component capability flag to blocklet configuration, enabling component-related functionality in the system
This update expands the blocklet capabilities configuration to support component features, providing more flexibility in how blocklets can be utilized within the system.
> feat(observability): support use as blocklet component

- packages/core/src/agents/agent.ts
- packages/core/src/loader/agent-js.ts
- packages/core/src/loader/agent-yaml.ts
- packages/core/src/loader/index.ts
- packages/core/src/loader/schema.ts
- packages/core/test-agents/test-agent-input-naming.yaml
- packages/core/test-agents/test-agent-with-default-input-skill.yaml
- packages/core/test-agents/test-agent-with-default-input.yaml
- packages/core/test/agents/__snapshots__/agent.test.ts.snap
- packages/core/test/agents/__snapshots__/ai-agent.test.ts.snap
- packages/core/test/agents/__snapshots__/mcp-agent.test.ts.snap
- packages/core/test/agents/__snapshots__/team-agent.test.ts.snap
- packages/core/test/agents/agent.test.ts
- packages/core/test/aigne/__snapshots__/aigne.test.ts.snap
- packages/core/test/loader/__snapshots__/agent-yaml.test.ts.snap
- packages/core/test/loader/agent-yaml.test.ts
- packages/core/test/prompt/__snapshots__/prompt-builder.test.ts.snap
- packages/core/test/utils/__snapshots__/event-stream.test.ts.snap
- packages/core/test/utils/__snapshots__/prompts.test.ts.snap
- packages/core/test/utils/__snapshots__/stream-utils.test.ts.snap
- packages/core/test/utils/__snapshots__/structured-stream-extractor.test.ts.snap
1. feat(core): support custom default input value for agent
usage:
```yaml
type: team
name: test_agent_with_default_input
skills:
- url: ./test-agent-with-default-input-skill.yaml
default_input:
title: Default Title
description:
$get: title
- type: ai
name: test_agent_with_default_input_skill2.yaml
input_schema:
type: object
...
default_input:
title: Another Default Title
description:
$get: title
```
Release Notes:
- New Feature: Added support for default input values in agent configurations, allowing users to specify preset values that are automatically merged with runtime inputs
- Enhancement: Improved agent loading system with better handling of YAML and JavaScript configurations
- Enhancement: Streamlined schema handling and key transformation logic across agent loaders
- …
> feat(core): support custom default input value for agent

- packages/cli/src/utils/load-aigne.ts
**Chore**: Environment Configuration Update
- Changed environment detection logic for Agent Hub provider integration to use `CI` environment variable instead of `NODE_ENV`
This is a minor internal change that improves how the system behaves in different environments, particularly in CI/CD pipelines. End users should not notice any difference in functionality.
> fix: ci lint

- packages/cli/package.json
- packages/cli/src/index.ts
- packages/cli/src/tracer/terminal.ts
- packages/cli/src/type.ts
- packages/cli/src/utils/listr.ts
- packages/cli/test/tracer/terminal.test.ts
- packages/cli/test/utils/load-aigne.test.ts
- packages/core/package.json
- packages/core/src/agents/agent.ts
- packages/core/src/aigne/context.ts
- pnpm-lock.yaml
1. feat(cli): add inquirer/prompts integrations for cli
usage:
```ts
import type { AgentInvokeOptions } from "@aigne/cli";
export default async function prompt(_input: any, options: AgentInvokeOptions) {
const name = await options.prompts.input({ message: "What is your name?" });
const age = await options.prompts.number({ message: "What is your age?" });
const color = await options.prompts.select({
message: "What is your favorite color?",
choices: [
{ name: "Red", value: "red" },
{ name: "Green", value: "green" },
{ name: "Blue", value: "blue" },
],
});
return { name, age, color };
}
```
Release Notes:
- New Feature: Enhanced CLI interaction with improved prompt handling and user input collection
- New Feature: Added support for multiple agent hooks, enabling more flexible workflow …
> feat(cli): add inquirer/prompts integrations for cli

- observability/ui/src/components/run/trace-detail-panel.tsx
- observability/ui/src/list.tsx
- packages/cli/package.json
- packages/cli/src/commands/connect.ts
- packages/cli/test/commands/connect.test.ts
- pnpm-lock.yaml
- support aigne connect status commands
Here are the concise release notes:
- Style: Enhanced UI layout with improved column widths and spacing in trace detail panels and list views for better readability
- New Feature: Added user information display to connection status command, showing user name, email, plan details, and billing URL
- Style: Improved table search element spacing and alignment for better visual consistency
Impact: Users will experience a more polished interface with better-organized trace information and gain access to their account details directly through the connection status command.
> fix: support aigne connect status more info

- packages/cli/package.json
- packages/cli/src/commands/connect.ts
- packages/cli/src/utils/aigne-hub-user.ts
- packages/cli/test/commands/connect.test.ts
- pnpm-lock.yaml
1. fix(cli): replace external dependency with built-in user subscription API
**Refactor**: 
- Internalized user information fetching functionality by replacing external dependency with local implementation
- Improved reliability of connection status checks in CLI
This change streamlines the dependency structure and makes the CLI more self-contained. Users should experience no functional changes, but the update provides better maintainability and reduces external dependencies. The connection status display remains unchanged from an end-user perspective.
> fix(cli): replace external dependency with built-in user subscription API

- observability/ui/src/components/run/trace-detail-panel.tsx
- support blocklet requests without leading slash
Based on the changes, here are the concise release notes:
- Bug Fix: Enhanced URL handling to support blocklet requests without leading slashes, improving compatibility and reducing request failures
The change ensures more flexible URL handling in the UI, making the system more robust when dealing with various URL formats. This is a minor but important fix that improves the reliability of blocklet requests.
> fix(observability): support blocklet requests without prefix

- packages/cli/src/commands/app.ts
- packages/cli/src/tracer/terminal.ts
- packages/cli/src/utils/listr.ts
1. fix(cli): persist prompts log and improve terminal output
🔄 Release Notes:
- Refactor: Enhanced terminal output handling for improved user experience and readability
- Refactor: Streamlined prompt interactions with better formatting and visual feedback
- Bug Fix: Resolved dependency installation issues by removing conditional skip logic, ensuring more reliable package updates
These changes focus on improving the CLI's user interface and reliability, making the terminal output more polished and ensuring dependencies are installed consistently. Users will notice clearer terminal feedback and more dependable package management.
> fix(cli): persist prompts log and improve terminal output

- packages/core/src/prompt/prompt-builder.ts
1. fix(core): filter empty memory content
- Bug Fix: Enhanced prompt message handling to filter out empty memory content, preventing potential issues with blank or invalid messages in conversation history
- Refactor: Improved input validation for memory content processing to ensure more reliable prompt generation
These changes improve the robustness of the prompt building system by ensuring only valid, non-empty content is included in conversations. Users will experience more reliable and cleaner interactions without empty or invalid messages appearing in their chat history.
> fix(core): filter empty memory content

- models/openai/src/openai-chat-model.ts
tool call function arguments should not be null
**Bug Fix**: 
- Fixed error handling in OpenAI chat model when processing tool calls with missing or undefined arguments. This prevents potential crashes when interacting with OpenAI's function calling features.
The change improves stability when working with OpenAI's tool/function calling capabilities by gracefully handling cases where function arguments are not provided, ensuring a more reliable experience for users implementing AI tools and function calls.
> fix: tool call function arguments should not be null

- .github/workflows/test-nodejs.yml
- packages/cli/src/cli.ts
- packages/cli/src/commands/aigne.ts
- packages/cli/src/tracer/terminal.ts
- packages/cli/src/utils/listr.ts
- packages/core/src/utils/logger.ts
- tests/nodejs/cli.test.ts
1. fix(cli): improve CLI prompts and output handling
Release Notes:
- Refactor: Improved CLI command handling for better error management and user experience
- Bug Fix: Enhanced terminal interaction stability and rendering performance
- Refactor: Modified default logging behavior to reduce unnecessary output
- Bug Fix: Resolved prompt handling issues in terminal interactions
- Chore: Streamlined command-line argument processing
These changes focus on improving the overall stability and user experience of the CLI tool, with particular emphasis on more reliable terminal interactions and streamlined command processing. Users should notice smoother operation and fewer unnecessary log messages during normal usage.
> fix(cli): improve CLI prompts and output handling

- packages/cli/src/utils/load-aigne.ts
1. create connect add app info
- New Feature: Added customization options for app branding in AIGNE CLI connections, allowing users to specify custom application names and logos
- Enhancement: Improved flexibility of the connection system by making app branding parameters optional, defaulting to AIGNE CLI standard branding when not specified
These changes enable developers to better integrate AIGNE CLI into their branded applications while maintaining backward compatibility with existing implementations.
> fix: create connect add app info

- packages/core/package.json
- packages/core/src/utils/camelize.ts
- packages/core/test/utils/camelize.test.ts
- pnpm-lock.yaml
1. fix(core): remove lodash dependency ensure core support both esm and cjs
Release Notes:
- Refactor: Removed Lodash dependency from core utilities in favor of native JavaScript methods, reducing bundle size and external dependencies
- Test: Enhanced test coverage for data type handling in object key conversion utilities
These changes improve the package's performance and maintainability while maintaining full compatibility with existing functionality. Users should experience no breaking changes while benefiting from a lighter dependency footprint.
> fix(core): remove lodash dependency ensure core support both esm and cjs

- packages/publish-docs/package.json
- packages/publish-docs/src/board.ts
- packages/publish-docs/src/index.ts
- packages/publish-docs/src/publisher.ts
- pnpm-lock.yaml
1. 创建 board 添加支持传入描述和图标
2. 检测 boardId 是否存在，不存在时创建 board 
3. 优化日志打印颜色
- New Feature: Enhanced board management with support for descriptions and cover images when creating boards
- New Feature: Improved duplicate board handling through automatic existence checks
- Style: Enhanced documentation URL visibility in console with colored formatting
These updates improve the board creation experience by adding more customization options and preventing duplicate boards. The console output is now more visually appealing with colored URLs, making documentation links easier to spot and access.
> fix: polish create board

- packages/publish-docs/src/board.ts
- packages/publish-docs/src/index.ts
- packages/publish-docs/src/publisher.ts
- packages/publish-docs/src/user.ts
1. 优化发布文档文案
2. 新增文档名称检查，如果名称重复
2.1 重复文档是由当前用户创建，则返回已存在的文档 board ，避免重复创建
2.2 重复文档由其他用户创建，提醒用户修改 board 名称，避免名称重复
Release Notes:
- New Feature: Added board name conflict resolution to prevent duplicate board creation
- New Feature: Implemented user session management for improved authentication
- Bug Fix: Enhanced board ownership validation through user session checks
- Refactor: Streamlined board publishing process with clearer console output
- Refactor: Removed unnecessary dependencies and simplified success messaging
These changes improve the reliability of board creation and management while adding proper user authentication. Users will experience more predictable behavior when creating boards with similar names and better security through session-based ownership validation.
> fix: implement board name conflict resolution with ownership validation

- models/aigne-hub/package.json
- models/aigne-hub/src/util/model.ts
- packages/cli/src/commands/run.ts
- packages/core/src/loader/index.ts
- pnpm-lock.yaml
https://team.arcblock.io/task/task/603059934631821312
- show current model info with masked API key in console
> fix: log current model info with masked API key in console

- models/aigne-hub/src/util/model.ts
https://team.arcblock.io/task/task/607863992588697600
ensure log prints only once
**Refactor**: 
- Optimized chat model information display to prevent duplicate messages, ensuring a cleaner and more professional user experience by showing the info box only once per session
This change improves the user interface by eliminating redundant information displays that could clutter the chat experience. The modification is subtle but enhances the overall polish of the application.
> fix: ensure log prints only once

- models/aigne-hub/src/blocklet-aigne-hub-model.ts
- models/aigne-hub/src/cli-aigne-hub-model.ts
- models/aigne-hub/src/index.ts
- models/aigne-hub/src/util/model.ts
-resolve circular dependency in aigne-hub
**Refactor**:
- Standardized model naming conventions across AIGNE Hub components
- Resolved circular dependencies in model architecture
**Note**: This is an internal refactoring that improves code maintainability and structure. No changes to functionality or user experience.
These changes lay the groundwork for more stable and maintainable future development while ensuring consistent naming patterns across the AIGNE Hub module.
> fix: resolve circular dependency in aigne-hub

- packages/cli/src/commands/hub.ts
- packages/cli/test/commands/hub.test.ts
https://team.arcblock.io/comment/discussions/fa2a70c8-94b8-4fcd-bd20-2e9f8fe0fbc4
improve feedback in AIGNE Hub commands
- New Feature: Enhanced AIGNE Hub CLI display with configurable credits and links visibility
- New Feature: Added direct URL support in the `hub connect` command
- Refactor: Simplified hub list display format for better readability
- Refactor: Standardized status messages from "configured" to "connected" for consistency
These changes improve the user experience when interacting with AIGNE Hub through the CLI, providing more flexible display options and streamlined connection workflows.
> fix(cli): improve feedback in AIGNE Hub commands

- models/aigne-hub/src/blocklet-aigne-hub-model.ts
- models/aigne-hub/src/cli-aigne-hub-model.ts
**Refactor**: 
- Standardized client identification across AIGNE hub components by implementing consistent DID header handling
- Enhanced client identification reliability by prioritizing BLOCKLET_APP_PID with hostname fallback
This change improves how AIGNE hub components identify themselves during model requests, ensuring more reliable and consistent client tracking. The update is transparent to end users while providing better system observability and troubleshooting capabilities.
> fix(model): add x-aigne-hub-client-did header for hub model requests

- packages/core/src/agents/agent.ts
1. feat(agents): add async memory recording option
> feat(agents): add async memory recording option

- packages/publish-docs/src/board.ts
https://team.arcblock.io/task/task/613250116647649280
1. 发布文档时可指定 id 创建 board
- New Feature: Added support for custom board IDs when creating documentation boards
- Enhancement: Improved board lookup logic to first check by ID, then by name
These changes allow users to specify their own unique identifiers when creating documentation boards, providing more control over board organization and management. The enhancement maintains backward compatibility with existing board creation workflows while adding this new customization option.
> fix: support create a new board by id

- packages/publish-docs/src/board.ts
- packages/publish-docs/src/index.ts
https://team.arcblock.io/task/task/613250116647649280
1. 发布文档新增保存 board meta 信息
保存的 meta 信息：
```json
{
"passports": [],
"translation": {
"title": {},
"desc": {}
},
"id": "hello-world-36",
"title": "Hello-World 6",
"desc": "Hello World 6 in all possible programmnig languages",
"icon": null,
"createdBy": "z1Vy8WkU2MiNsskXFVVmzLurvSuejG7Ns3U",
"cover": "https://bbqawfllzdt3pahkdsrsone6p3wpxcwp62vlabtawfu.did.abtnet.io/image-bin/uploads/537a7ba21377af0b21cdf992a9b7737c.png",
"type": "doc",
"position": 520000,
"meta": {
"category": [
"getStarted"
],
"githubRepoUrl": "git@github.com:blackbird71SR/Hello-World.git",
"commitSha": "ea95f03e1901fc856dd9eaa2b69c2b28c7c4e92e",
"languages": [
"zh",
"en"
]
},
"createdAt": "2025-08-22T08:18:49.925Z",
"updatedAt": "2025-08-22T08:18:49.925Z"
}
``` …
> fix: save board meta info

- models/gemini/src/gemini-image-model.ts
- models/gemini/test/gemini-image-model.test.ts
- models/ideogram/package.json
- models/ideogram/src/ideogram-image-model.ts
- models/ideogram/test/ideogram-image-model.test.ts
- pnpm-lock.yaml
https://team.arcblock.io/task/task/574783421633527808
- support gemini-2.0-flash model for image model
- support ideogram model for image model 
Release Notes:
- New Feature: Enhanced image generation capabilities with support for both Gemini and Imagen models
- New Feature: Added flexible model version selection for Ideogram image generation
- Refactor: Improved URL handling and endpoint construction for image generation services
- Refactor: Streamlined configuration options for image generation requests
These updates provide users with more versatile image generation options and better control over model selection. The changes maintain backward compatibility while expanding the available features for both Gemini and Ideogram services.
> fix: support gemini-2.0-flash model for image model

- packages/cli/package.json
- packages/cli/src/utils/inquirer/checkbox.ts
- packages/cli/test/utils/inquirer/checkbox.test.ts
- packages/cli/tsconfig.json
- pnpm-lock.yaml
1. fix: resolve checkbox multi-select issues and add comprehensive test
Release Notes:
- Refactor: Enhanced checkbox multi-select component with improved selection handling and keyboard navigation
- Test: Added comprehensive test coverage for checkbox component functionality
- Chore: Updated TypeScript configuration settings
These changes improve the reliability and usability of the CLI's checkbox selection interface, ensuring a more robust user experience when making multiple selections. The enhanced keyboard navigation and selection handling make the interface more accessible and user-friendly.
> fix: resolve checkbox multi-select issues and add comprehensive test

- packages/core/src/prompt/template.ts
1. fix(core): handle relative path correctly
- Refactor: Enhanced template loader functionality to better handle relative and absolute file paths
This change improves how template files are loaded by implementing proper path resolution. Users working with template files in different directories will experience more reliable template loading behavior, especially when using relative paths in their configurations.
> fix(core): handle relative path correctly

- models/aigne-hub/README.md
- models/gemini/README.md
- models/ideogram/README.md
- models/ideogram/src/ideogram-image-model.ts
Release Notes:
- New Feature: Added support for "ideogram-v3" as the default image model
- Enhancement: Improved model selection flexibility by allowing model configuration through credentials
- Enhancement: Streamlined model parameter handling with automatic fallback to credential-defined models
These changes provide users with access to the latest ideogram model version while making the model selection process more flexible and robust. Users can now configure their preferred model through credentials, with automatic fallback behavior ensuring consistent operation.
> chore: update images model readme

- models/aigne-hub/src/aigne-hub-image-model.ts
- add model for image mode input params
Release Notes:
- Enhancement: Extended image model configuration options in AIGNE Hub integration, allowing for more flexible model parameter handling
- Bug Fix: Improved model fallback behavior by utilizing credential-based defaults when specific options aren't provided
These changes provide more reliable and configurable image processing capabilities while ensuring smoother operation when working with different model configurations. Users will experience more consistent behavior when interacting with AIGNE Hub image models.
> fix: add model for image mode input params

- packages/cli/src/tracer/terminal.ts
1. fix: add file protocol to local file links in terminal tracer
- Bug Fix: Improved handling of local file paths in terminal output by correctly formatting them with the file protocol
- Enhancement: Better distinction between local files and web URLs in CLI terminal traces, making navigation and debugging more intuitive
The changes ensure proper display and linking of file paths in the terminal, providing a more reliable experience when working with local files through the CLI interface.
> fix: add file protocol to local file links in terminal tracer

- packages/transport/src/http-server/server.ts
**New Feature**:
- Added error hook support to HTTP server responses, allowing developers to execute custom callbacks when errors occur during response handling
This enhancement enables better error monitoring and custom error handling capabilities in HTTP server implementations while maintaining existing error response behavior. Users can now attach either single hooks or arrays of hooks to handle error scenarios according to their application needs.
> fix: support error hooks for AIGNEHTTPServer

- models/gemini/src/gemini-chat-model.ts
- models/gemini/test/gemini-chat-model.test.ts
- models/openai/src/openai-chat-model.ts
- models/openai/test/openai-chat-model.test.ts
- packages/core/src/agents/agent.ts
- packages/core/src/agents/chat-model.ts
- packages/core/src/utils/json-schema.ts
- packages/core/src/utils/type-utils.ts
- packages/core/test/utils/type-utils.test.ts
1. fix: support optional field sturectured output for gemini
2. fix: remove zod instanceof check to allow any version of zod
Release Notes:
New Feature:
- Added support for optional fields in structured output for both OpenAI and Gemini chat models
- Introduced flexible JSON schema validation modes ("anyOf" and "optional")
Bug Fix:
- Improved handling of null and undefined values in structured outputs
- Fixed schema validation to better handle optional fields
Documentation:
- Fixed spelling and grammar in documentation, including proper capitalization of "Gemini"
These changes make the chat models more flexible when dealing with structured outputs, allowing developers to specify which fields are optional while maintaining strict validation where needed.
> fix: support optional field sturectured output for gemini

- models/gemini/src/gemini-chat-model.ts
- models/gemini/test/gemini-chat-model.test.ts
1. fix(gemini): should include at least one user message
Bug Fix: Improved message handling in Gemini chat model
- Fixed an issue where conversations without explicit user messages could fail
- Enhanced message role validation to ensure proper chat flow
- Automatically converts system messages to user messages when needed to maintain conversation compatibility
This update ensures more reliable chat interactions with the Gemini model by preventing potential conversation failures, particularly in scenarios where system messages are present but user messages are missing.
> fix(gemini): should include at least one user message

- examples/nano-banana/image-generation.ts
- examples/nano-banana/package.json
- models/aigne-hub/src/aigne-hub-image-model.ts
- models/aigne-hub/src/index.ts
- models/aigne-hub/src/utils/model.ts
- models/aigne-hub/test/_mocks_/server.ts
- models/aigne-hub/test/chat.test.ts
- models/aigne-hub/test/image.test.ts
- models/aigne-hub/test/utils/model.test.ts
- models/doubao/src/doubao-image-model.ts
- models/doubao/test/doubao-image-model.test.ts
- models/gemini/src/gemini-image-model.ts
- models/gemini/test/gemini-image-model.test.ts
- models/ideogram/src/ideogram-image-model.ts
- models/ideogram/test/ideogram-image-model.test.ts
- models/openai/src/openai-image-model.ts
- models/openai/test/openai-image-model.test.ts
- packages/core/src/agents/ai-agent.ts
- packages/core/src/agents/chat-model.ts
- packages/core/src/agents/image-agent.ts
- packages/core/src/agents/image-model.ts
- packages/core/src/agents/model.ts
- packages/core/src/index.ts
- packages/core/src/prompt/prompt-builder.ts
- packages/core/test/agents/chat-model.test.ts
- packages/core/test/agents/image-agent.test.ts
- packages/core/test/agents/image-model.test.ts
- pnpm-lock.yaml
1. feat: improve image model architecture and file handling
usage:
```ts
import { AIGNEHubImageModel } from "@aigne/aigne-hub";
import { FileOutputType } from "@aigne/core";
const model = new AIGNEHubImageModel({
model: "openai/gpt-image-1",
// model: "google/gemini-2.5-flash-image-preview",
// model: "ideogram/ideogram-v3",
// model: "doubao/doubao-seedream-4-0-250828",
});
const result = await model.invoke({
prompt: "Change to cartoon style",
image: [
{
type: "url",
url: "https://hub.aigne.io/image-bin/uploads/c9121213809f72a63d0fb9d793b4f175.png",
},
],
outputType: FileOutputType.local,
});
console.log(result);
```
Release Notes:
- New Feature: Added support for file-based image generation across multiple AI providers (OpenAI, Gemini, Ideogram, Doubao)
- New Feature: Introduced base64 …
> feat: improve image model architecture and file handling

- models/ideogram/package.json
- pnpm-lock.yaml
> fix: move zod from devDependencies to dependencies in ideogram model

- observability/api/api/opentelemetry/exporter/http-exporter.ts
- packages/sqlite/src/retry.ts
1. fix: improve SQLite busy error handling and observability logging
Release Notes:
- Chore: Enhanced error logging in observability system to provide clearer context and more informative messages when issues occur
- Chore: Improved SQLite database resilience by adjusting retry parameters for better handling of locked database states
These changes improve system reliability and debugging capabilities without requiring any user action. The adjustments help maintain smoother database operations under high load conditions and make troubleshooting more effective through better error reporting.
> fix(core): tune SQLite busy error handling and observability logging

- packages/cli/src/cli.ts
- packages/cli/src/commands/aigne.ts
- packages/cli/src/commands/app.ts
- packages/cli/src/utils/spinner.ts
- packages/cli/test/commands/app.test.ts
1. fix(cli): improve app loading reliability with force upgrade on error
Release Notes:
- New Feature: Added loading spinner animation for better visual feedback during CLI operations
- Bug Fix: Improved reliability of app loading with automatic force upgrade on failures
- Refactor: Enhanced error handling and command processing for more robust CLI execution
- Chore: Streamlined version management and installation procedures
These changes focus on improving the CLI's user experience by providing clearer visual feedback during operations and making the tool more resilient when handling errors or failed loads.
> fix(cli): improve app loading reliability with force upgrade on error

- packages/cli/src/utils/aigne-hub/model.ts
- packages/cli/src/utils/load-aigne.ts
- packages/cli/src/utils/workers/run-aigne-in-child-process-worker.ts
- packages/cli/src/utils/yargs.ts
- packages/cli/test-agents/aigne.yaml
- packages/cli/test/commands/app.test.ts
- packages/cli/test/commands/run.test.ts
- packages/cli/test/utils/load-aigne.test.ts
1. fix(cli): load image model base on agent definition
```yaml
type: image
image_model: google/gemini-2.5-flash-image-preview
name: image
instructions: Draw a cute cat with swings
```
```shell
aigne run xxx xxx --image-model google/gemini-2.5-flash-image-preview
```
Release Notes:
- New Feature: Added support for image model integration, allowing users to specify and use image models alongside chat models
- New Feature: Enhanced CLI interface with improved model selection syntax (provider[/model]) for both chat and image models
- Refactor: Replaced hardcoded OpenAI implementation with a configurable approach for image model handling
- Refactor: Streamlined model initialization process with unified credential and environment variable handling
These changes enable users to work with image …
> fix(cli): load image model base on agent definition

- packages/cli/src/utils/aigne-hub/model.ts
- packages/cli/test-agents/aigne.yaml
- packages/cli/test/utils/load-aigne.test.ts
- packages/core/src/loader/schema.ts
- packages/core/test-agents/aigne.yaml
- packages/core/test/loader/loader.test.ts
1. feat: support custom extra model options in agent yaml file
```yaml
model:
model: openai/gpt-4o-mini
custom_option: 1
xxx: xxx
image_model:
model: openai/gpt-image-1
quality: standard
xxx: xxx
```
New Feature:
- Added support for custom model options in both chat and image models
- Enhanced model configuration flexibility through YAML configuration files
Test:
- Improved test coverage for model loading and configuration validation
These changes allow users to specify additional model-specific options when configuring their AI models, providing greater customization capabilities while maintaining backward compatibility. The enhanced configuration system supports both chat and image model types with flexible option handling.
> feat: support custom extra model options in agent yaml file

- packages/core/src/agents/team-agent.ts
- packages/core/src/loader/agent-yaml.ts
- packages/core/test-agents/team-agent-with-reflection.yaml
- packages/core/test/agents/team-agent.test.ts
- packages/core/test/loader/__snapshots__/agent-yaml.test.ts.snap
1. feat: support custom reflection error message
```yaml
type: team
name: test-team-agent-with-reflection
description: Test team agent with reflection
skills:
- chat.yaml
reflection:
reviewer: team-agent-reviewer.yaml
is_approved: approved
custom_error_message: Test custom error message for reflection
```
> feat: support custom reflection error message

- models/aigne-hub/src/utils/model.ts
- packages/cli/src/utils/aigne-hub/model.ts
1. fix: standardize URL parameter naming from url to baseURL
**Refactor**: 
- Standardized URL parameter naming across the codebase by changing from `url` to `baseURL` for improved code consistency and maintainability
This change harmonizes the naming convention for URL-related properties throughout the system, making the codebase more predictable and easier to maintain. While this is primarily an internal refactoring change, it helps ensure more reliable API interactions and reduces potential confusion for developers working with the codebase.
> fix: standardize URL parameter naming from url to baseURL

- packages/cli/src/utils/aigne-hub/credential.ts
- packages/cli/src/utils/aigne-hub/model.ts
- packages/cli/test/utils/aigne-hub/credential.test.ts
- packages/cli/test/utils/load-aigne.test.ts
1. fix(cli): add environment variable support for AIGNE Hub credentials
usage:
```shell
export AIGNE_HUB_API_KEY=xxxxxxxxxx
export AIGNE_HUB_API_URL=https://hub.aigne.io # optional
aigne doc generate
```
New Feature:
- Added environment variable support for AIGNE Hub credentials
- Introduced `AIGNE_HUB_API_KEY` for setting API authentication
- Added optional `AIGNE_HUB_API_URL` for custom API endpoint configuration
These changes provide users with more flexibility in managing their AIGNE Hub credentials through environment variables, offering an alternative to configuration files. This enhancement improves security by allowing sensitive credentials to be managed through environment variables and simplifies deployment across different environments.
> fix(cli): add environment variable support for AIGNE Hub credentials
