AIGNE-io/aigne-framework

examples/mcp-github/package.json
examples/mcp-puppeteer/package.json
examples/mcp-sqlite/package.json
examples/workflow-code-execution/package.json
examples/workflow-concurrency/package.json
examples/workflow-group-chat/package.json
examples/workflow-handoff/package.json
examples/workflow-orchestrator/package.json
examples/workflow-reflection/package.json
examples/workflow-router/package.json
examples/workflow-sequential/package.json
package.json
packages/agent-library/package.json
packages/cli/package.json
packages/core/package.json
packages/core/src/loader/index.ts
packages/core/src/utils/mcp-utils.ts
packages/core/test/loader/loader.test.ts
packages/test-utils/package.json
pnpm-lock.yaml

1. remove usage of new Node.js exists API for compatibility
2. update deps
- Updated file existence checking to use modern Node.js APIs, ensuring better compatibility with current Node.js versions
- Improved internal URI template handling for more reliable resource management
These changes are internal improvements that maintain existing functionality while modernizing the codebase. Users should experience no changes in behavior, but the updates provide better stability and compatibility with current Node.js environments.

fix: remove usage of new Node.js exists API for compatibility

---

docs/cli.md
docs/cli.zh.md
examples/mcp-github/package.json
examples/mcp-puppeteer/package.json
examples/mcp-sqlite/package.json
examples/workflow-code-execution/package.json
examples/workflow-concurrency/package.json
examples/workflow-group-chat/package.json
examples/workflow-handoff/package.json
examples/workflow-orchestrator/package.json
examples/workflow-reflection/package.json
examples/workflow-router/package.json
examples/workflow-sequential/package.json
packages/cli/package.json
packages/cli/src/commands/run.ts
packages/cli/test/commands/run.test.ts
packages/core/package.json
packages/core/src/execution-engine/execution-engine.ts
packages/core/src/loader/agent-js.ts
packages/core/src/loader/agent-yaml.ts
packages/core/src/loader/index.ts
pnpm-lock.yaml

1. feat(cli): add `--download-dir` save agents to special folder for `run` command
2. feat(cli): support setting model by `--mode-provider` & `--model-name` option for `run` command
3. fix(loader): allow setting tool choice in yaml agent file
4. fix(loader): allow setting agent name through `agent.agent_name` in js agent file
Release Notes:
- New Feature: Added `--download-dir` CLI option to specify custom directory for agent package downloads
- New Feature: Introduced `tool_choice` configuration in YAML to control tool selection behavior with options "auto", "none", "required", or "router"
- Enhancement: Improved agent name resolution with better fallback handling for backward compatibility
These updates provide more flexibility in managing agent downloads and configuration, while …

feat(cli): support model and download customization for aigne run

---

packages/cli/src/commands/run.ts
packages/cli/src/utils/run-chat-loop.ts

1. display progressing for `run` command
- Refactor: Enhanced CLI initialization with visual progress indicators for package downloads and setup
- Style: Simplified chat output by removing redundant input message display
These changes improve the user experience by providing clearer feedback during agent initialization and streamlining the chat interface. Users will now see a progress bar when downloading and setting up packages, making it easier to track the startup process.

fix(cli): display progressing for `run` command

---

packages/cli/src/commands/run.ts
packages/cli/test/commands/run.test.ts

1. fix(cli): ensure dir exists before extract package
- Bug Fix: Improved package extraction reliability by ensuring target directories exist before extraction
- Test: Enhanced test stability by using dynamic UUIDs instead of hardcoded paths
These changes improve the robustness of the package extraction process, preventing potential failures when target directories don't exist. The testing improvements help maintain reliable test execution in CI/CD pipelines.

fix(cli): ensure dir exists before extract package

---

packages/core/src/agents/agent.ts
packages/core/src/utils/type-utils.ts
packages/core/test/agents/agent.test.ts

1. fix(dx): custom error message for agent input/output validation
Example:
```
ERROR: Agent test-agent-plus input check arguments error: a: Expected number, received string, b: Expected number, received string
```
- New Feature: Enhanced schema validation for agent inputs/outputs with clearer error messages
- Test: Added comprehensive validation test coverage for agent parameters
- Refactor: Improved type checking system using Zod for more robust parameter validation
These changes provide developers with better feedback when agent parameters don't match expected schemas, making it easier to identify and fix type mismatches, especially for numeric values. Error messages are now more descriptive and actionable.

fix(dx): custom error message for agent input/output validation

---

packages/cli/package.json
packages/cli/src/global.d.ts
packages/cli/src/tracer/terminal.ts
packages/cli/test/.env.test
packages/cli/test/tracer/__snapshots__/terminal.test.ts.snap
packages/cli/test/tracer/terminal.test.ts
pnpm-lock.yaml

1. feat(cli): render output message with markdown highlight
- New Feature: Added markdown rendering support in CLI output, enabling better formatting of AI responses with headers, lists, code blocks, and other markdown elements
- Enhancement: Improved readability of terminal output through proper rendering of markdown syntax
These changes enhance the user experience by making AI responses more visually structured and easier to read in the terminal, supporting standard markdown formatting conventions that users are familiar with.

feat(cli): render output message with markdown highlight

---

.github/workflows/test-examples.yml
examples/chat-bot/README.md
examples/chat-bot/index.ts
examples/mcp-blocklet/README.md
examples/mcp-blocklet/index.ts
examples/mcp-github/README.md
examples/mcp-github/index.ts
examples/mcp-puppeteer/README.md
examples/mcp-puppeteer/index.ts
examples/mcp-sqlite/README.md
examples/mcp-sqlite/index.ts
examples/workflow-code-execution/README.md
examples/workflow-code-execution/index.ts
examples/workflow-concurrency/README.md
examples/workflow-concurrency/index.ts
examples/workflow-group-chat/README.md
examples/workflow-group-chat/index.ts
examples/workflow-handoff/README.md
examples/workflow-handoff/index.ts
examples/workflow-orchestrator/README.md
examples/workflow-orchestrator/index.ts
examples/workflow-reflection/README.md
examples/workflow-reflection/index.ts
examples/workflow-router/README.md
examples/workflow-router/index.ts
examples/workflow-sequential/README.md
examples/workflow-sequential/index.ts
packages/cli/package.json
packages/cli/src/bunwrapper.ts
packages/cli/src/tracer/terminal.ts

1. fix: example chat-bot launch error
2. use `bunwrapper`(from @aigne/cli) to launch examples
- New Feature: Added `bunwrapper` utility to improve Bun command execution handling, automatically detecting local Bun installations and falling back to npx when needed
- Refactor: Simplified command execution in example scripts by using the new `bunwrapper` utility
- Chore: Enhanced GitHub Actions workflow reliability by ensuring proper binary executable installation
- Refactor: Streamlined chat-bot example command execution for better maintainability
These changes improve the developer experience by providing more robust Bun command handling and simplifying example script execution across the project.

fix: use bunwrapper launch examples

---

.github/workflows/test-examples.yml
docs/agent-development.md
docs/agent-development.zh.md
packages/cli/templates/default/chat.yaml
packages/core/package.json
packages/core/src/loader/agent-js.ts
packages/core/src/loader/agent-yaml.ts
packages/core/src/loader/index.ts
packages/core/src/utils/camelize.ts
packages/core/test-agents/chat.yaml
packages/core/test/utils/camelize.test.ts
pnpm-lock.yaml

1. feat: support set memory in agent yaml
```yaml
name: chat
description: Chat agent
instructions: |
You are a helpful assistant that can answer questions and provide information on a wide range of topics.
Your goal is to assist users in finding the information they need and to engage in friendly conversation.
memory: true
```
Release Notes:
- New Feature: Added flexible snake_case to camelCase conversion utility with support for nested objects and configurable transformation depth
- Refactor: Enhanced agent loading system with improved memory configuration support in YAML files
- Refactor: Streamlined agent creation process with more consistent property handling across JS and YAML loaders
Impact: Users can now define memory configurations in YAML files and benefit from more reliable …

feat: support set memory in agent yaml

---

packages/core/src/prompt/prompt-builder.ts
packages/core/src/utils/type-utils.ts
packages/core/test/prompt/prompt-builder.test.ts
packages/core/test/utils/type-utils.test.ts

1. fix(core): deduplicate tools for chat model
Release Notes:
- New Feature: Added array deduplication functionality to prevent duplicate tools when combining multiple AI agent skills
- Refactor: Improved handling of tool combinations in prompt builder for more efficient agent configurations
- Test: Added comprehensive test coverage for deduplication features
These changes enhance the reliability of AI agent configurations by automatically preventing duplicate tools when combining skills from different sources, resulting in more predictable and efficient agent behavior.

fix(core): ensure no deduplicate tools for chat model

---

examples/mcp-blocklet/index.ts

from internal test feedback
1. ensure BLOCKLT_APP_URL is valid before starting the example
2. remove custom timeout for mcp-agent transport, default to 60s
No
- New Feature: Added URL validation for blocklet applications to ensure proper connectivity
- Bug Fix: Removed custom 8-second timeout in favor of standard 60-second timeout for more reliable connections
- Enhancement: Improved error handling for invalid blocklet URLs with graceful process termination
These changes enhance the reliability and robustness of blocklet application connections while providing clearer feedback when connection issues occur.

chore: polish mcp-blocklet example

---

docs/cookbook.md
docs/cookbook.zh.md
packages/core/src/agents/ai-agent.ts
packages/core/test/agents/ai-agent.test.ts

- fix #104 
1. fix(core): default catch tool errors and continue processing
- New Feature: Added configurable error handling for AI agent tools via `catchToolErrors` option
- Test: Added comprehensive test coverage for error handling scenarios
This release introduces more flexible error handling control for AI agents. Users can now choose whether tool execution errors should be caught and processed (default behavior) or propagate as exceptions by setting the `catchToolErrors` option. This enables better error management strategies depending on application needs.

fix(core): default catch tool's error and continue processing

---

biome.json
docs/cookbook.md
docs/cookbook.zh.md
examples/workflow-reflection/index.ts
examples/workflow-reflection/usages.ts
packages/core/src/agents/agent.ts
packages/core/src/agents/user-agent.ts
packages/core/src/aigne/aigne.ts
packages/core/src/aigne/context.ts
packages/core/src/aigne/message-queue.ts
packages/core/test/agents/memory.test.ts
packages/core/test/agents/user-agent.test.ts
packages/core/test/aigne/aigne.test.ts
packages/core/test/aigne/context.test.ts
packages/test-utils/tsconfig.build.json

- fix #62 
- fix https://github.com/AIGNE-io/aigne-framework/issues/86
1. fix(core): handle response for UserAgent automatically in pub/sub mode
Release Notes:
- Refactor: Streamlined pub/sub messaging system for improved reliability and performance
- New Feature: Enhanced topic subscription handling with array-based operations
- New Feature: Added flexible message payload support (Message, MessagePayload, string)
- Refactor: Improved agent architecture with better memory management
- New Feature: Simplified workflow reflection examples for better developer experience
- Test: Expanded test coverage for core messaging and agent functionality
These changes improve system stability and developer experience while maintaining backward compatibility. Users will benefit from more flexible …

fix(core): handle response for UserAgent automatically in pub/sub mode

---

packages/cli/src/tracer/terminal.ts
packages/core/src/agents/ai-agent.ts
packages/core/src/agents/team-agent.ts
packages/core/src/aigne/context.ts
packages/core/src/server/server.ts
packages/core/src/utils/stream-utils.ts
packages/core/test/agents/agent.test.ts
packages/core/test/aigne/aigne.test.ts
packages/core/test/client/client.test.ts
packages/core/test/models/chat-model.test.ts
packages/core/test/models/claude-chat-model.test.ts
packages/core/test/models/deepseek-chat-model.test.ts
packages/core/test/models/gemini-chat-model.test.ts
packages/core/test/models/ollama-chat-model.test.ts
packages/core/test/models/open-router-chat-model.test.ts
packages/core/test/models/openai-chat-model.test.ts
packages/core/test/models/xai-chat-model.test.ts
packages/core/test/utils/stream-utils.test.ts
tsconfig.json

1. fix: response.headers.toJSON is not a function
2. refactor: remove unnecessary stream utils
-
- Modernized stream handling across the entire codebase by adopting native async iteration capabilities
- Improved performance and reliability of streaming responses in all chat models
- Simplified internal stream processing architecture
- Updated TypeScript configuration to better support modern streaming features
This update streamlines the internal streaming implementation while maintaining full compatibility with existing APIs. Users should experience improved reliability and potentially better performance when working with streaming responses, though no API changes are required.

fix(core): response.headers.toJSON is not a function

---

package.json
pnpm-lock.yaml
scripts/remark-plugin-clean-code.ts
scripts/ts-utils.ts
scripts/tsconfig.json
scripts/typedoc-plugin-clean-code.ts
typedoc.base.js

1. chore(docs-builder): remove variable statements(include spyOn) from e…
- none
🔄 Release Notes:
- Refactor: Improved documentation tooling with a new local TypeDoc plugin for cleaner code examples
- Chore: Replaced external `@aigne/typedoc-plugin-example-utils-ts` package with in-house solution
- Refactor: Enhanced code processing utilities with better modularity and organization
- Chore: Updated TypeScript configuration to support explicit file extensions
These changes primarily improve the development infrastructure and documentation generation process. End users will benefit from cleaner, more consistent code examples in the documentation, though most changes are internal improvements to maintain code quality and reduce external dependencies.

chore(docs-builder): remove variable statements(include spyOn) from example code

---

packages/core/package.json
packages/core/src/agents/agent.ts
packages/core/src/agents/chat-model.ts
packages/core/test/agents/chat-model.test.ts
packages/transport/package.json
packages/transport/src/http-client/client.ts
packages/transport/src/http-server/server.ts
packages/transport/test/http-client/http-client.test.ts
pnpm-lock.yaml

1. fix: automatically convert tool names to a valid format
Release Notes:
- New Feature: Added automatic tool name sanitization to ensure compatibility with function calling APIs, converting hyphens and spaces to underscores while preserving original names in responses
- Enhancement: Extended transport layer to support both string and structured message inputs, providing more flexibility in how users can format their requests
- Test: Added comprehensive test coverage for tool name conversion functionality
Impact: Users can now use tools with any naming convention without worrying about API compatibility, and have more options for formatting their input messages when making requests.

fix: automatically convert tool names to a valid format

---

packages/core/src/prompt/prompt-builder.ts
packages/core/test/prompt/prompt-builder.test.ts

1. fix(core): exclude nested skills from final tool list in invokable skill
**Bug Fix**: Improved skill collection handling in prompt generation
- Fixed how nested skills are processed when building agent prompts
- Invokable skills now correctly exclude their nested skills from the tool list
- Ensures more accurate and relevant tool availability for agents
This change provides more precise control over which skills are available to agents during execution, preventing potential confusion or unintended access to nested capabilities. Users will experience more predictable agent behavior, particularly when working with complex skill hierarchies.

fix(core): exclude nested skills from final tool list in invokable skill

---

packages/agent-library/src/default-memory/default-memory-storage/index.ts
packages/agent-library/src/default-memory/default-memory-storage/migrations/001-init.ts
packages/agent-library/src/default-memory/index.ts
packages/agent-library/src/fs-memory/index.ts
packages/agent-library/test/default-memory/__snapshots__/default-memory-storage.test.ts.snap
packages/agent-library/test/default-memory/__snapshots__/default-memory.test.ts.snap
packages/agent-library/test/default-memory/default-memory-storage.test.ts
packages/agent-library/test/default-memory/default-memory.test.ts
packages/agent-library/test/fs-memory/fs-memory.test.ts
packages/core/src/agents/agent.ts
packages/core/src/agents/ai-agent.ts
packages/core/src/agents/mcp-agent.ts
packages/core/src/memory/memory.ts
packages/core/src/memory/recorder.ts
packages/core/src/memory/retriever.ts
packages/core/test/prompt/prompt-builder.test.ts

1. feat: support remember custom fields from message
```ts
const memory = new DefaultMemory({
recorderOptions: {
rememberFromMessageKey: "message",
},
});
```
Refactor: Major overhaul of the memory system architecture
- New Feature: Flexible memory configuration through function handlers
- New Feature: Custom field extraction capabilities in message processing
- New Feature: Enhanced message structure with role-based content organization
- Refactor: Improved agent type system for better message handling flexibility
- Test: Comprehensive test coverage for new memory system features
These changes provide developers with more control over memory handling and message processing while maintaining backward compatibility. The new architecture enables more sophisticated memory …

feat: support remember custom fields from message

---

examples/chat-bot/aigne.yaml
examples/chat-bot/index.js
examples/chat-bot/package.json
examples/mcp-server/aigne.yaml
examples/mcp-server/index.js
examples/mcp-server/package.json
packages/cli/src/cli.ts
packages/cli/src/commands/aigne.ts
packages/cli/src/commands/run.ts
packages/cli/src/commands/serve-mcp.ts
packages/cli/src/commands/test.ts
packages/cli/test/cli.test.ts

1. feat(cli): support executing aigne.yaml via shebang (#!/usr/bin/env aigne)
ainge.yaml
```yaml
#!/usr/bin/env aigne
chat_model:
name: gpt-4o-mini
temperature: 0.8
agents:
- agents/chat.yaml
```
- New Feature: Added shebang support for direct execution of AIGNE configuration files using `#!/usr/bin/env aigne`
- Refactor: Simplified example projects by removing Node.js wrapper scripts in favor of native AIGNE file execution
- Chore: Updated internal command handlers to support file-based execution mode
These changes streamline the workflow for AIGNE users by allowing configuration files to be executed directly as scripts, eliminating the need for separate wrapper files. Users can now run AIGNE files with standard Unix-like shebang syntax.

feat(cli): support executing aigne.yaml via shebang (#!/usr/bin/env aigne)

---

packages/cli/src/commands/aigne.ts
packages/cli/test/commands/aigne.test.ts

1. fix(cli): set run as the default command
- New Feature: Simplified CLI usage by making `run` the default command
- Test: Added verification for default command behavior
These changes streamline the AIGNE framework CLI experience by allowing users to execute the `run` command without explicitly specifying it. Users can now use `aigne [options]` instead of `aigne run [options]`, making the CLI more intuitive and user-friendly while maintaining all existing functionality.

fix(cli): set run as the default command

---

packages/core/src/agents/agent.ts
packages/core/src/utils/stream-utils.ts
packages/core/test/agents/agent.test.ts
packages/core/test/aigne/context.test.ts

1. fix(core): ensure output is a record type
```shell
$ bun run test.ts        
aigne:core:error Invoke agent calculate failed with error: Error: expect to return a record type such as {result: ...}, but got (number): 110
aigne:core:error     at objectToAgentResponseStream (/Users/chao/Projects/blocklet/aigne-framework/packages/core/lib/esm/utils/stream-utils.js:7:19)
aigne:core:error     at invoke (/Users/chao/Projects/blocklet/aigne-framework/packages/core/lib/esm/agents/agent.js:311:27)
aigne:core:error     at processTicksAndRejections (native:7:39) +0ms
aigne:core:error Invoke agent calculate failed with error: Error: expect to return a record type such as {result: ...}, but got (number): 110
aigne:core:error     at objectToAgentResponseStream …
```

fix(core): ensure output is a record type for FunctionAgent

---

packages/core/src/loader/agent-js.ts
packages/core/src/loader/agent-yaml.ts
packages/core/src/loader/schema.ts
packages/core/test-agents/external-schema-agent-nested.yaml
packages/core/test-agents/external-schema-agent.yaml
packages/core/test-agents/external-schema-first.yaml
packages/core/test-agents/external-schema-second.yaml
packages/core/test-agents/external-schema-third.yaml
packages/core/test-agents/external-schema.yaml
packages/core/test/loader/__snapshots__/agent-yaml.test.ts.snap
packages/core/test/loader/agent-yaml.test.ts

1. feat(core): support include external schema for input/output schema
file: agent.yaml
```yaml
name: external-schema-agent
description: External schema agent
input_schema: schema.yaml
output_schema: schema.yaml
```
file: schema.yaml
```yaml
type: object
properties:
message:
type: string
description: Message to process
other: ./other-schema.yaml
required:
- message
```

feat(core): support external files as agent input/output schema

---

packages/core/src/agents/team-agent.ts
packages/core/test/agents/team-agent.test.ts

1. fix(core): check if skills is empty before TeamAgent processes
- New Feature: Added validation to TeamAgent requiring at least one skill to be defined
- Test: Added unit tests to verify TeamAgent skill validation
This change prevents invalid TeamAgent configurations by ensuring at least one skill is specified during initialization. This improves reliability by failing fast with clear error messages rather than allowing misconfigured agents to run.

fix(core): check if skills is empty before TeamAgent processes

---

packages/publish-docs/src/converter/index.ts
packages/publish-docs/test/index.test.ts

Fixes how inline code is parsed inside markdown links. Right now, links with inline code render incorrectly (see screenshot below).
- Bug Fix: Improved rendering of markdown links containing inline code blocks (e.g. [`example`](link))
- Test: Added test coverage for markdown link parsing with inline code blocks
These changes ensure that documentation links containing code snippets are displayed correctly, providing a better reading experience for users viewing the generated documentation.

fix(docs): should parse inline code inside markdown links

---

packages/publish-docs/src/converter/index.ts
packages/publish-docs/src/generator.ts
packages/publish-docs/src/index.ts
packages/publish-docs/src/utils/slugify.ts
scripts/publish-docs.ts

1. publish docs option add slug without ext parameter, default value is true
- New Feature: Added `slugWithoutExt` option to control whether .md extensions are removed from generated slugs in documentation paths
- Enhancement: Introduced `DOC_ROOT_DIR` environment variable support for flexible documentation root directory configuration
- Refactor: Improved slug generation consistency across documentation processing pipeline
These changes provide more flexibility in documentation path handling and organization, allowing users to maintain their preferred URL structure while supporting custom root directory configurations.

feat(docs): support optional extension suffix for doc slug

---

packages/core/src/loader/agent-js.ts
packages/core/src/loader/agent-yaml.ts
packages/core/src/loader/index.ts
packages/core/test-agents/test-agent-with-default-input-skill-js.js
packages/core/test-agents/test-agent-with-default-input.yaml
packages/core/test/loader/__snapshots__/agent-yaml.test.ts.snap

1. fix(core): function agent should use common schema from yaml definition
Release Notes:
- New Feature: Added support for function-based agents, allowing developers to define agents using JavaScript functions with input schema validation
- Refactor: Streamlined agent loading system to handle multiple agent formats (YAML and JS) more consistently
- Test: Enhanced test coverage for function agents and input validation scenarios
These changes make it easier to create agents using JavaScript functions while maintaining the same validation and configuration capabilities available in YAML-based agents. The unified loading system provides a more reliable and maintainable foundation for agent development.

fix(core): function agent should use common schema from yaml definition

---

packages/core/src/agents/team-agent.ts
packages/core/test/agents/__snapshots__/team-agent.test.ts.snap
packages/core/test/agents/team-agent.test.ts

1. feat(core): add reflection mode support to TeamAgent
usage:
```ts
const teamAgentWithReflection = TeamAgent.from({
inputSchema: z.object({
topic: z.string(),
}),
skills: [
AIAgent.from({
instructions: `\
Write a article about {{topic}}
<previous-content>
{{content}}
</previous-content>
<feedback>
{{feedback}}
</feedback>
`,
outputKey: "content",
}),
],
reflection: {
reviewer: AIAgent.from({
instructions: `\
You are a reviewer. Please review the following article and provide feedback.
topic: {{topic}}
generated content:
{{content}}
`,
outputSchema: z.object({
approved: z.boolean(),
feedback: z.string().optional(),
}),
}),
isApproved: (o) => o.approved,
maxIterations: 3,
},
});
```

feat(core): add reflection mode support to TeamAgent

---

models/aigne-hub/src/hub-model.ts

- Updated environment variable configuration for the AigneHub chat model to use `BLOCKLET_AIGNE_API_URL` instead of `BLOCKLET_AIGNE_API_BASE_URL`
This is a minor configuration update that ensures consistent environment variable naming across the system. No functional changes or user-facing impacts are expected from this change.

fix(core): update blocklet key name

---

packages/publish-docs/src/publisher.ts
packages/publish-docs/src/types.ts

1. add auto open document url feature
- New Feature: Added automatic browser opening of published documentation URLs
- Enhancement: Improved console feedback during documentation publishing process
These changes streamline the documentation workflow by automatically opening published docs in the default browser after successful publishing. Users no longer need to manually copy/paste URLs, making the documentation access more convenient and immediate.

fix: add auto open document url feature

---

packages/core/package.json
packages/core/src/agents/team-agent.ts
packages/core/src/loader/agent-yaml.ts
packages/core/test-agents/team.yaml
packages/core/test/agents/__snapshots__/team-agent.test.ts.snap
packages/core/test/agents/team-agent.test.ts
pnpm-lock.yaml

1. feat(core): add concurrency support for team agent
usage
```yaml
type: team
name: test-team-agent
iterate_on: sections
concurrency: 2
```
Release Notes:
- New Feature: Added concurrent processing support to TeamAgent, allowing parallel execution of agent tasks for improved performance
- New Feature: Introduced `concurrency` configuration option to control parallel processing behavior
- Test: Added comprehensive test coverage for concurrent execution scenarios
These changes enable users to significantly improve processing speed by running multiple agent tasks simultaneously while maintaining control over resource utilization through the concurrency setting.

feat(core): add concurrency support for team agent

---

packages/cli/src/cli.ts
packages/cli/src/commands/aigne.ts
packages/cli/src/commands/app.ts
packages/cli/test/commands/__snapshots__/aigne.test.ts.snap
packages/cli/test/commands/aigne.test.ts
packages/cli/test/commands/app.test.ts

1. show help message if no any subcommand
2. polish tips for `aigne observe` command
3. correctly show the app's last version after upgraded
CLI Improvements:
- Enhancement: Improved error handling with clearer help messages when commands are missing or incorrect
- Enhancement: Added "-v" shorthand alias for version command for easier access
- Bug Fix: Version numbers now display correctly in upgrade notifications and success messages
- Enhancement: Updated command help text styling and instructions for better readability
- Enhancement: Added requirement for subcommands to prevent invalid command usage
These changes focus on making the CLI more user-friendly with better error messages, consistent version reporting, and clearer command guidance.

fix(cli): improve help display and command handling

---

packages/cli/src/commands/app.ts
packages/cli/src/commands/connect.ts
packages/cli/src/commands/run.ts
packages/cli/src/commands/serve-mcp.ts
packages/cli/src/commands/test.ts
packages/cli/src/utils/aigne-hub-user.ts
packages/cli/src/utils/load-aigne.ts
packages/cli/test/utils/load-aigne.test.ts

https://team.arcblock.io/task/task/607863992588697600
1. Support setting `aigne-hub-url` via CLI options.
2. Skip AIGNE Hub selection prompt if a custom URL is provided.
3. Add first-time setup prompt to choose AIGNE Hub connection type.
4. Update AIGNE Connect to check and display connection status.
New Feature:
- Added support for custom AIGNE Hub service URLs via `--aigne-hub-url` option across CLI commands
- Enhanced connection management with support for both official and self-hosted AIGNE Hub instances
- Improved prompt handling system to support input-type prompts alongside select prompts
These changes give users more flexibility in connecting to different AIGNE Hub environments and provide better control over their agent interactions through expanded prompt …

feat(cli): support config custom AIGNE Hub service URL

---

packages/core/src/utils/structured-stream-extractor.ts
packages/core/test/agents/ai-agent.test.ts
packages/core/test/utils/__snapshots__/structured-stream-extractor.test.ts.snap
packages/core/test/utils/structured-stream-extractor.test.ts

1. fix(core): auto trim trailing whitespace for AIAgent with structuredStreamMode enabled
**Bug Fix**: 
- Improved text processing in structured streams by properly handling trailing whitespace
- Fixed inconsistencies in text segment output when using structured stream mode
**Test**:
- Enhanced test coverage for whitespace handling in structured streams
These changes improve the quality and consistency of text output when using structured streams, ensuring cleaner text segments without unwanted whitespace artifacts. Users will experience more predictable and polished text processing results, particularly in applications that rely on structured stream processing.

fix(core): auto trim trailing whitespace for AIAgent with structuredStreamMode enabled

---

packages/core/src/agents/chat-model.ts

1. fix(core): hide internal prop toolsMap from trace logs
- **Refactor**: Modified how internal tool mappings are handled to prevent unnecessary logging, improving trace output clarity without affecting functionality.
This is a minor internal change that helps keep logs cleaner and more focused on relevant information. End users will see more concise trace logs without any changes to the actual behavior or capabilities of the system.

fix(core): hide internal prop toolsMap from trace logs

---

packages/publish-docs/src/generator.ts

1. 发布文档添加处理更多语言
- New Feature: Expanded multilingual documentation support to include 10 additional languages:
- Chinese (Traditional)
- Japanese
- Korean
- Spanish
- French
- German
- Portuguese
- Russian
- Italian
- Arabic
This enhancement enables users to access documentation in their preferred language, making the platform more accessible to a global audience.

feat(cli): add multilingual support for document publishing

---

packages/cli/src/commands/app.ts

1. fix(cli): force upgrade app while load app error
- Bug Fix: Improved error handling during application startup to prevent crashes when cache loading fails. The system will now automatically attempt to upgrade instead of failing, providing a more reliable experience for users.
The change makes the CLI more resilient by gracefully handling cache-related issues during startup, ensuring users can continue using the application even if the cache becomes corrupted or inaccessible.

fix(cli): force upgrade app while load app error

---

packages/cli/src/tracer/terminal.ts
packages/cli/src/utils/listr.ts
packages/core/src/agents/agent.ts
packages/core/src/agents/team-agent.ts
packages/core/src/aigne/context.ts
packages/core/test/aigne/__snapshots__/aigne.test.ts.snap
packages/sqlite/src/index.node.ts
packages/sqlite/src/retry.ts
packages/sqlite/test/retry.test.ts
packages/transport/test/http-client/__snapshots__/http-client.test.ts.snap

1. fix: improve error handling and propagation in agent execution
2. fix(sqlite): add retry mechanism with exponential backoff for sqlite
Release Notes:
- Bug Fix: Enhanced error handling in CLI with improved error messages and visual feedback
- Bug Fix: Resolved SQLite database locking issues with automatic retry mechanism
- Refactor: Optimized core agent performance and reliability
- Refactor: Improved SQLite database performance with WAL optimizations
These changes improve system stability and reliability by addressing database locking issues, enhancing error reporting, and optimizing core performance. Users will experience fewer database-related interruptions and clearer error messages when issues occur.

fix(cli): reduce memory usage of AIGNE CLI

---

packages/core/src/prompt/template.ts

1. fix(core): resolve nested prompt file correctly
**Refactor**:
- Improved prompt file resolution by ignoring system directories like `node_modules` and `.git`
- Enhanced nested prompt file discovery for better template organization
This update streamlines how the system locates and processes prompt templates, making the file resolution process more reliable and efficient. Users working with nested template structures will experience more predictable template loading behavior.

fix(core): resolve nested prompt file correctly

---

packages/core/src/loader/agent-yaml.ts
packages/core/src/loader/index.ts
packages/core/src/prompt/template.ts
packages/core/test-agents/prompts/nested/prompt-c.md
packages/core/test-agents/prompts/nested/prompt-d.md
packages/core/test-agents/prompts/prompt-b.md
packages/core/test/loader/loader.test.ts

1. fix(core): improve nested prompt file resolution
Refactor: Simplified Agent Configuration System
- Refactor: Streamlined instruction handling for AI and image agents with improved path resolution
- Refactor: Enhanced error handling for missing image agent instructions
- Refactor: Simplified prompt template resolution with direct file path construction
- Test: Added verification for nested prompt file resolution
These changes improve the reliability and maintainability of agent configurations while maintaining backward compatibility. Users should experience more predictable behavior when specifying instruction paths and working with prompt templates.

fix(core): improve nested prompt file resolution

---

packages/cli/src/utils/inquirer/checkbox.ts
packages/cli/test/utils/inquirer/checkbox.test.ts

1. feat(cli): support ctrl+a select all items for prompts.checkbox
Release Notes:
- New Feature: Added Ctrl+A shortcut to select all items in checkbox prompts
- Enhancement: Improved help text visibility and clarity in search mode
- Test: Added comprehensive test coverage for select-all functionality
These changes enhance the checkbox prompt interface by allowing users to quickly select all items using Ctrl+A, making bulk selections more efficient. The help text improvements provide clearer guidance during search operations.

feat(cli): support ctrl+a select all items for prompts.checkbox

---

packages/core/src/loader/agent-yaml.ts

1. fix: handle absolute paths in agent YAML prompt URLs
Bug Fix: Improved path handling for agent YAML prompt URLs
- Bug Fix: Fixed handling of absolute file paths in agent YAML configurations, ensuring both absolute and relative paths work correctly when loading prompt files
- Impact: Users can now specify either absolute or relative paths in their agent YAML files without path resolution issues
This change makes the system more flexible and reliable when working with different file path formats in agent configurations.

fix: handle absolute paths in agent YAML prompt URLs

---

packages/cli/src/commands/app.ts
packages/cli/test/commands/app.test.ts

We need to support beta version apps (DocSmith, WebSmith)
1. Support using beta version of sub apps by using AIGNE_USE_BETA_APPS
- New Feature: Added support for beta application versions through the `AIGNE_USE_BETA_APPS` environment variable, allowing developers to test pre-release versions of applications
- Test: Enhanced test coverage for beta version selection and fallback behavior
This update enables developers to opt into beta versions of applications by setting an environment variable, while maintaining stable release access as the default behavior. The system automatically falls back to stable versions if beta versions are unavailable.

feat(cli): support using beta apps with environments

---

packages/cli/src/commands/hub.ts
packages/cli/src/utils/aigne-hub-user.ts
packages/cli/test/commands/hub.test.ts

- https://team.arcblock.io/task/task/622367461622153216
Refactor: Streamlined hub commands by merging status functionality into `hub info`
- New Feature: Enhanced credit display showing available vs. used balance
- New Feature: Improved hub selection interface with connected hub visibility
- Refactor: Simplified command structure by removing redundant `hub status` command
- Documentation: Updated command descriptions and user prompts for clarity
These changes provide a more intuitive command interface while maintaining all existing functionality. Users can now access hub status information through the `hub info` command with improved credit balance visibility.

fix(cli): tune aigne hub status and deprecate aigne hub info

---

blocklets/aigne-runtime/src/locales/en.tsx
blocklets/aigne-runtime/src/locales/zh.tsx

correct flat import, remove default import error
**Chore**: 
- Updated internationalization (i18n) module imports to use the correct named import `flatten` instead of `flat`
This is a minor internal maintenance change that updates how the localization files handle their dependencies. There is no impact on end-users or the application's functionality, as both English and Chinese language support continue to work as before.

fix: correct flat import, remove default import error

---

.github/workflows/test-nodejs.yml
packages/cli/src/commands/create.ts
packages/cli/src/commands/deploy.ts
packages/cli/src/utils/workers/load-aigne.ts
tests/nodejs/docsmith.test.ts

1. fix: replace import.meta.dirname with Node 20 compatible dirname approach
Here are the concise release notes:
- Fixed Windows compatibility issues with npm when using Node.js 22.0
- Resolved Node.js 20 compatibility issues in CLI commands
- Updated file path resolution mechanism to support newer Node.js versions
These changes ensure smoother operation across different Node.js versions and operating systems, particularly benefiting Windows users running Node.js 22.0. No changes to core functionality or user-facing features were made.

fix: replace import.meta.dirname with Node 20 compatible dirname approach

---

packages/cli/src/tracer/terminal.ts
packages/cli/test/tracer/terminal.test.ts
packages/core/src/aigne/context.ts

1. fix(cli): options.prompts should always available
2. refactor: check parameters for context.invoke strictly

fix(cli): options.prompts should always available

---

packages/core/src/loader/agent-yaml.ts
packages/core/test-agents/chat.yaml
packages/core/test/loader/__snapshots__/agent-yaml.test.ts.snap
packages/core/test/loader/agent-yaml.test.ts

1. fix(core): add `include_input_in_output` option for agent definition
```yaml
type: ai
name: chat
include_input_in_output: true
```
- New Feature: Added `includeInputInOutput` configuration option for agents, allowing developers to control whether the original input text should be included in agent responses
- Test: Updated test suite to verify new configuration behavior
This enhancement gives developers more granular control over agent output formatting, helping to streamline response handling and reduce redundancy when input repetition isn't needed.

fix(core): add `include_input_in_output` option for agent definition

---

packages/core/src/agents/agent.ts
packages/core/test/agents/agent.test.ts

1. fix(core): agent should not emit error event if retried
Bug Fix: Improved Agent Error Handling
- Fixed incorrect error event emission in Agent class to prevent duplicate error notifications
- Now only emits "agentFailed" event when retry attempts are exhausted, providing more accurate error state reporting
- Ensures applications using the Agent class receive proper error signals for handling failures
Test:
- Added comprehensive test coverage for Agent error handling scenarios
This change improves reliability and predictability of error handling behavior for applications using the Agent framework.

fix(core): agent should not emit error event if retried
